'use client';
import Link from 'next/link';
import { useState } from 'react';
import { copy } from '@/lib/copy';
import { type Status, updateDemo, useDemo } from '@/lib/demo-store';
const statuses: Record<Status, string> = { new: 'Mới', progress: 'Đang xử lý', resolved: 'Đã xử lý' };
export default function OwnerDashboard() {
  const demo = useDemo(); const [open, setOpen] = useState<string | null>(null); const [error, setError] = useState('');
  const rated = demo.records.filter(r => r.rating > 0); const pending = demo.records.filter(r => r.message && r.status !== 'resolved');
  function save(id: string, field: 'note' | 'status', value: string) { const ok = updateDemo(data => { const r = data.records.find(r => r.id === id); if (r) { if (field === 'note') r.note = value; else r.status = value as Status; } }); setError(ok ? '' : 'Chưa lưu được thay đổi trên trình duyệt.'); }
  return <main className="dashboard-wrap"><header className="dashboard-nav"><Link href="/t/demo">← Trang khách</Link><span>NFC FEEDBACK / OWNER</span><span className="demo-pill">BẢN THỬ</span></header>
    <div className="dashboard-heading"><div><p className="eyebrow">4RÂU BARBERSHOP</p><h1>Tiếng nói khách hàng</h1><p className="muted">Những điều khách muốn bạn biết.</p></div></div>
    <aside className="demo-disclosure">Dashboard mẫu — chưa có đăng nhập. Dữ liệu chỉ lưu trên trình duyệt này, không phải dữ liệu khách thật hoặc hệ thống riêng tư đã triển khai.</aside>
    <section className="metrics" aria-label="Tổng quan"><div><span>Lượt chấm sao</span><strong data-testid="rating-count">{rated.length}</strong></div><div><span>Hài lòng nội bộ</span><strong data-testid="rating-average">{rated.length ? (rated.reduce((s,r) => s+r.rating,0)/rated.length).toFixed(1).replace('.',',') : '—'}<small>/5</small></strong></div><div><span>Góp ý chưa xử lý</span><strong data-testid="pending-count">{pending.length}</strong></div></section>
    <section className="inbox"><div className="inbox-heading"><h2>Đánh giá & góp ý</h2><span className="muted small">Mẫu + trải nghiệm bạn đang thử</span></div>{demo.records.map(r => <article key={r.id} className="feedback-row" data-testid={`record-${r.id}`}><div className={`score score-${r.rating}`}>{r.rating || '—'}<span>/5</span></div><div className="row-content"><div className="row-meta"><strong>{r.id === 'THỬ01' ? 'Trải nghiệm bạn đang thử' : `Khách mẫu ${r.id}`}</strong><span className="muted small">{r.source}</span></div><p>{r.message || 'Chỉ chấm sao · Chưa có góp ý bằng chữ'}</p><div className="row-meta"><span className="muted small">{r.message && `${copy.vi[r.topic]} · `}{r.updatedAt.includes('T') && !r.updatedAt.startsWith('Mẫu') ? new Date(r.updatedAt).toLocaleString('vi-VN') : r.updatedAt}</span>{r.message && <span className={`status-pill ${r.status}`}>{statuses[r.status]}</span>}</div><button className="text-button" onClick={() => setOpen(open === r.id ? null : r.id)} aria-expanded={open === r.id}>{open === r.id ? 'Thu gọn ↑' : 'Xem & xử lý ↗'}</button>{open === r.id && <div className="owner-detail">{r.message && <label>Trạng thái<select value={r.status} onChange={e => save(r.id,'status',e.target.value)}>{Object.entries(statuses).map(([v,label]) => <option key={v} value={v}>{label}</option>)}</select></label>}<label>Ghi chú nội bộ<textarea rows={3} maxLength={2000} value={r.note} onChange={e => save(r.id,'note',e.target.value)} placeholder="Việc cần làm để cải thiện trải nghiệm…"/></label><p className="small muted">Tự lưu trong bản thử. Không gửi ghi chú này cho khách.</p></div>}</div></article>)}</section>
    <p className="google-metric">Lượt bấm Google: <strong>{demo.googleClicks}</strong> <span className="muted">· Chưa xác nhận khách đã đăng review.</span></p><p role="status" className="error">{error}</p>
  </main>;
}
