'use client';
import { useCallback, useEffect, useState } from 'react';
type Row={id:string;rating:number|null;message:string;status:string;note:string;updated_at:string};
export default function ShopDashboard({slug,name}:{slug:string;name:string}) {
 const [rows,setRows]=useState<Row[]>([]);const [page,setPage]=useState(1);const [notice,setNotice]=useState('');
 const url=`/api/owner/${encodeURIComponent(slug)}`;
 const load=useCallback(async()=>{try{const r=await fetch(`${url}?page=${page}`,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();setRows(data.records);setNotice('');}catch{setRows([]);setNotice('Không tải được dữ liệu hoặc phiên đăng nhập đã hết hạn.');}},[url,page]);
 useEffect(()=>{const controller=new AbortController();fetch(`${url}?page=${page}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{setRows(data.records);setNotice('');}).catch(()=>{if(!controller.signal.aborted){setRows([]);setNotice('Không tải được dữ liệu.');}});return()=>controller.abort();},[url,page]);
 async function save(e:React.FormEvent<HTMLFormElement>,id:string){e.preventDefault();const form=new FormData(e.currentTarget);try{const r=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:form.get('status'),note:form.get('note')})});if(!r.ok)throw Error();await load();setNotice('Đã lưu trên máy chủ.');}catch{setNotice('Chưa lưu được thay đổi.');}}
 return <main className="dashboard-wrap"><header className="dashboard-nav"><a href={`/${slug}`}>← Trang khách</a><button onClick={load}>Làm mới</button></header><h1>{name} · Góp ý khách hàng</h1><p>Dữ liệu PostgreSQL · Trang {page}</p><p role="status">{notice}</p>{rows.map(r=><article className="feedback-row" key={r.id}><div className="score">{r.rating??'—'}/5</div><div className="row-content"><p>{r.message||'Chỉ chấm sao'}</p><p>{new Date(r.updated_at).toLocaleString('vi-VN')}</p><form onSubmit={e=>save(e,r.id)}><label>Trạng thái<select name="status" defaultValue={r.status}><option value="new">Mới</option><option value="progress">Đang xử lý</option><option value="resolved">Đã xử lý</option></select></label><label>Ghi chú nội bộ<textarea name="note" defaultValue={r.note} maxLength={2000}/></label><button>Lưu</button></form></div></article>)}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Trang trước</button><button disabled={rows.length<50} onClick={()=>setPage(p=>p+1)}>Trang sau</button></main>;
}
